In [2]:
from dmi.observation import DMIOpenDataClient,DMIBulkDataClient
from IPython.display import display, HTML
import json

In [ ]:
f = open('key.json',)
data = json.load(f)

In [3]:
base = DMIOpenDataClient(api_key=data['api_key'])
df = base.get_observations(100) # can give the data limit here, by default it is 1000
df.head()

,lat,long,Geometry_types,id,type,amp,created,observed,sensors,strokes,lightning_type
0,21.0333,55.1475,Point,10229287953820005514752103331-03,Feature,-0.3,2020-09-22T07:19:06.108531Z,2002-06-01T10:53:15.382000Z,"1,2,3,5,6",1.0,cloud to cloud
1,21.8251,54.4186,Point,10229287991510005441862182511-03,Feature,-0.3,2020-09-22T07:19:06.108825Z,2002-06-01T10:53:19.151000Z,"1,2,6",1.0,cloud to ground(-ve)
2,23.2202,55.0019,Point,10229289185530005500192322021-03,Feature,-0.3,2020-09-22T07:19:06.108926Z,2002-06-01T10:55:18.553000Z,"1,2,3,4,5,6",1.0,cloud to ground(-ve)
3,20.3758,54.4169,Point,1022929261172000544169203758108,Feature,0.8,2020-09-22T07:19:06.109017Z,2002-06-01T11:01:01.172000Z,"1,2,4",1.0,cloud to ground (+ve)
4,15.3336,53.4127,Point,10229294346640005341271533361-10,Feature,-1.0,2020-09-22T07:19:06.109105Z,2002-06-01T11:03:54.664000Z,"1,2,3,4,5,6",1.0,cloud to ground(-ve)

Bulk Data Download for 2020

In [7]:
bulkbase = DMIBulkDataClient(api_key=data['api_key'])
bulk_df = bulkbase.get_bulk_observations() # can give the year by deafult 2020
bulk_df.head()

,15.7837,52.7303,Point,1546376926836000527303157837146,Feature,4.6,2020-09-22T07:13:08.860305Z,2019-01-01T21:08:46.836000Z,"4,5,6",1,cloud to ground (+ve)
0,15.8644,52.7044,Point,15463710789570005270441586441-23,Feature,-2.3,2020-09-22T07:13:08.860220Z,2019-01-01T19:31:18.957000Z,"2,4",1,cloud to ground(-ve)
1,13.6915,52.2481,Point,15463653177210005224811369151-22,Feature,-2.2,2020-09-22T07:13:08.860135Z,2019-01-01T17:55:17.721000Z,"2,4",1,cloud to cloud
2,13.7101,52.1361,Point,15463650018320005213611371011-23,Feature,-2.3,2020-09-22T07:13:08.860048Z,2019-01-01T17:50:01.832000Z,"2,4",1,cloud to ground(-ve)
3,13.5707,52.2818,Point,15463639161140005228181357071-35,Feature,-3.5,2020-09-22T07:13:08.859942Z,2019-01-01T17:31:56.114000Z,"2,4",1,cloud to ground(-ve)
4,6.3187,58.6846,Point,1546327306867000586846631871209,Feature,20.9,2020-09-22T07:13:08.859845Z,2019-01-01T07:21:46.867000Z,"3,5,6",1,cloud to ground (+ve)